### ISSUE TITLE
content shifts when using dropdowns with scrolllock

### ISSUE THREAD

**Issue by jxjj** [UMN-LATIS/CLA-vue-template#24]
some component libraries (e.g. radix, shadcn) use scroll-lock and focus trapping with dropdown menus to allow users to navigate through dropdown options with arrows.

When this happens, the scrollbar disappears and the whole page content shifts:
![ScreenShot 2024-12-26 at 13 23 07](https://github.com/user-attachments/assets/a883f36e-eb90-40c1-a799-9c176e889e53)

Libraries that implement scroll-lock prevent page content shifting over by adding padding-right equal to the scroll-width when the lock is active. However, we have `body { padding: 0 !important}` which is overriding the css. Removing `!important` is probably sufficient to fix this and shouldn't impact other projects.

In the meanwhile, a workaround for shadcn/radix components is:

```css
/**
This is a fix for body content shift when dropdown is open.
The issue is the cla-vue-template is setting `padding: 0 !important`
on the body element. Then, when a dropdown is opened, scrolllock is
is activated (by radix) applying overflow: hidden to the body. Radix
accomodates for the change by setting a padding when the scrollbar
disapppears, but the `padding: 0 !important` prevents it from working.

Here we manually set the padding-right to the scrollbar width when
the body has a focus guard, which seems to coincide with scrolllock
(but may not always be the case?).

A better fix is probably to remove the padding: 0 !important from
the cla-vue-template, but this is a quick fix for now.
**/
@layer base {
  body:has([data-radix-focus-guard]) {
    padding-right: var(--scrollbar-width) !important;
  }
}
```
